### ISSUE TITLE
Header text isn't center aligned with header images

### ISSUE THREAD

**Issue by figchutney** [figchutney/google-homepage#1]
The header text isn't _quite_ aligned with the header images - it's very close, but not quite there, and I'm not sure what's causing the slight mis-alignment.

Treating the `<ul>` as a flex-box setting `align-items: center` has almost done the trick, but it's still not quite centered.

**Comment by figchutney** [comment]
Solved by adding `vertical-align: middle` to the `<img>` tags, as below. While the `<li>` items were vertically aligned _themselves_ within a flex-box, the `<img>` elements _within_ the `<li>` items were aligned (by default presumably) to the baseline. Aligning the `<img>` elements to vertically within the `<li>` items did the trick. Thanks to @Kavian77 for the fix.

```css
#nine-squares img {
    height: 16px;
    width: 16px;
    vertical-align: middle;
}

#user-icon img {
    height: 32px;
    width: 32px;
    border-radius: 50%;
    vertical-align: middle;
}
```
