### ISSUE TITLE
CSS needs to be refactored to remove unnecessary complexity

### ISSUE THREAD

**Issue by figchutney** [figchutney/google-homepage#2]
At the moment the CSS is quite a bit longer than it could be. I.d like to refactor unnecessarily complex code snippets like:

```css
.search-box {
        border-style: solid;
        border-width: 1px;
        border-color: #ccc;
}
```
into snippets like:

```css
.search-box {
        border: 1px solid #ccc;
}
```

There are also a few rules I've repeated multiple times, that could be moved into a document-wide rule.
